### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by wrist** [wrist/nbmediasplit#1]
* [x] add interface to specify output ipynb filename
* [x] add interface to specify path prefix embedded in ipynb
* [x] add test files
* [x] extract multiple audio tags in a cell
* [x] change cui arguments to create output directory as optional
* [x] release to pypi

next release

* [x] extract markdown cell's attachment
    * now the script extracts markdown cell's attachment as the same manner as code cell output
    * but in the future release, attachment will be treated separatedly
* [x] extract from old format ipynb(consider when `outputs[*]["data"]["image/png"]` is list)
* [x] code format using autopep8
* [x] check to work on WIndows
* [x] use invoke instead of Makefile
* [x] add more test (use pytest)
* [x] ci using github actions
* [x] remove `-c` option
